// <auto-generated />
namespace Scheduler_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial6));
        
        string IMigrationMetadata.Id
        {
            get { return "202103052049558_initial-6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
